definitions:
  username:
    name: username
    description: User's username.
    in: formData
    required: true
    type: string,
    example: 'a@a.com'
  ApiKey:
    name: 'api-key'
    in: 'header'
    required: true,
    type: 'string'
    enum:
      - '1'
      - '2'
      - '3'
    default: 'xxxxx'
  login:
      name: login
      in: body
      description: create user
      schema:
        type: object
        required:
          - name
        properties:
          name:
            type: string
        example:
          name: Jhon
  token:
    name: authorization
    in: header
    description: lo que sea

  prueba:
      description: Prueba de definicion
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            type: object
        403:
          $ref: '#responses/403'

  prueba2:
    post:
      description: Prueba 2 de definicion
      tags: [Pruebas]
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            type: object
        403:
          $ref: '#responses/403'
  
  prueba3:
    get:
      description: Prueba 3 de definicion
      tags: [Pruebas]
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            type: object
        403:
          $ref: '#responses/403'
  
  prueba4:
    get:
      description: Prueba 4 de definicion
      tags: [Pruebas 2]
      produces:
        - application/json
      responses:
        200:
          description: Success
          schema:
            type: object
        403:
          $ref: '#responses/403'