/authentication:
    post:
      description: Login to the application
      tags: [Authentication]
      produces:
        - application/json
      parameters:
        - $ref: '#/definitions/login'
      responses:
        200:
          $ref: '#responses/200'
        403:
          $ref: '#responses/403'
    delete:
      description: Login to the application
      tags: [Authentication]
      produces:
        - application/json
      parameters:
        - $ref: '#/definitions/username'
      schema:
      responses:
        200:
          description: login
          schema:
            type: object